env:
  browser: true
  es2021: true
extends:
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks

rules:
  import/no-cycle: [2, { maxDepth: 1}]
  import/prefer-default-export: 0
  import/extensions: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/prop-types: 0